;で読み飛ばすようにした
zavtrone/boleppybot pull request #1
Opened 2021-11-03 12:53 UTC by arataku

;で読み飛ばすようにしました

2021-11-03 13:03 UTC, zavtrone commented on src/tts.js
> +            if (Content.startsWith(";")) {
```js
Content.startWith(";")
```
ではなく
```js
content.startWith(";")
```
では？

2021-11-03 13:05 UTC, zavtrone requested changes
contentではなくContentとなっている箇所があります

2021-11-03 13:05 UTC, zavtrone commented on src/tts.js
> +            if (Content.startsWith(";")) {
```js
Content.startsWith(";")
```
ではなく
```js
content.startsWith(";")
```
では？

2021-11-03 13:10 UTC, arataku commented on src/tts.js
> +            if (Content.startsWith(";")) {
ふぁっっっ
oh...
ちなみにmessage.content.startsWith(";")にしないといけなかったりします？それともcontent.startsWithでおｋ？

2021-11-03 13:30 UTC, zavtrone commented on src/tts.js
> +            if (Content.startsWith(";")) {
content.startsWithでお願いします

2021-11-04 04:29 UTC, zavtrone approved these changes

2021-11-04 04:30 UTC, merged